require_relative 'c3po/my_information_page'
require_relative 'c3po/my_information_page_filler'
require_relative 'c3po/athlete_profile_page'
require_relative 'c3po/academics_page'
require_relative 'c3po/academics_page_filler'
