source 'https://rubygems.org'

gem 'eyes_selenium'
gem 'faraday'
gem 'logger'
gem 'mechanize'
gem 'minitest'
gem 'minitest-ci'
gem 'minitest-spec'
gem 'minitest-reporters'
gem 'net-ssh'
gem 'parallel'
gem 'rubocop', '~> 0.49.1'
gem 'rubyzip'
gem 'selenium-webdriver'
gem 'xml-simple'
