source 'https://rubygems.org'

gem 'api-auth'
gem 'csv'
gem 'ey-hmac', '2.2.0'
gem 'faraday'
gem 'gmail'
gem 'jwt'
gem 'mechanize'
gem 'minitest'
gem 'minitest-ci'
gem 'net-ssh'
gem 'nokogiri'
gem 'oj'
gem 'os'
gem 'parallel'
gem 'rest-client'
gem 'rubocop'
gem 'ruby-pg'
gem 'rubyzip'
gem 'selenium-webdriver'
gem 'tiny_tds'
gem 'watir'
gem 'watir-scroll'
gem 'xml-simple'
gem 'ffaker'

gem 'pry'

gem 'eyes_selenium', '3.14.3' # this is only here because of WWW code existence
