source 'https://rubygems.org'

gem 'csv'
gem 'eyes_selenium'
gem 'gmail'
gem 'jwt'
gem 'mechanize'
gem 'minitest'
gem 'minitest-ci'
gem 'net-ssh'
gem 'nokogiri', '~> 1.8.1'
gem 'os'
gem 'parallel'
gem 'rest-client'
gem 'rubocop', '~> 0.49.1'
gem 'rubyzip'
gem 'selenium-webdriver'
gem 'watir'
gem 'watir-scroll'
gem 'watir-webdriver'
gem 'xml-simple'
