# Browserstack key
browserstack_key: 'sdUUPjomNV13XYurTgXg'

# Fasttrack Admin login
fasttrack_admin:
  username: 'automation'
  password: 'Secure.123'

# TED coach/admin login
ted_coach:
  username: 'ncsa.automation+ted@gmail.com'
  password: 'password'
  free_username: 'noel.ronnie1@yopmail.com'
  free_password: 'ncsa'

ted_admin:
  username: 'ncsa.automation@gmail.com'
  password: 'mixed_martial_arts_678594'

# sample video user login
video_user:
  username: 'elite2'
  password: 'ncsa'

# automation gmail
gmail:
  username: 'ncsa.automation@gmail.com'
  app_pass: 'axkhemudrqgwaldq'
  password: 'oz4efpwaYpJivWZDbAGrJMJf'
  google_voice: '802-676-0642'

# Coach RMS
coach_rms:
  username: 'lajball@yopmail.com'
  password: 'ncsa123'
