# Fasttrack Admin login
fasttrack_admin:
  username: 'automation'
  password: 'Secure.123'

# TED coach login
ted_coach:
  username: 'cdickson197@gmail.com'
  password: 'ncsa'

# sample video user login
video_user:
  username: 'elite2'
  password: 'ncsa'

# automation gmail
gmail:
  username: 'ncsa.automation@gmail.com'
  app_pass: 'axkhemudrqgwaldq'
  password: 'oz4efpwaYpJivWZDbAGrJMJf'
  google_voice: '802-676-0642'

# Coach RMS
coach_rms:
  username: 'lajball@yopmail.com'
  password: 'ncsa123'
