# New recruit creds
recruit:
  firstName: 'qa'
  lastName: 'automation'
  homePhonePh1: '888'
  homePhonePh2: '222'
  homePhonePh3: '3333'
  parent1FirstName: 'mom'
  parent1LastName: 'mom'
  parent1PhonePh1: '408'
  parent1PhonePh2: '333'
  parent1PhonePh3: '2222'

# Fake credit billing info
credit_billing:
  order_card_holder_first_name: 'q'
  order_card_holder_mi_name: 'a'
  order_card_holder_last_name: 'automation'
  order_card_number: '4242424242424242'
  order_cvv_code: '123'
  order_account_holder_phone: '4445556666'
  order_account_holder_email: 'automation@ncsasports.org'
  order_billing_address: '1333 N Kingsbury'
  order_billing_city: 'Chicago'
  order_billing_zip: '60642'

# Fake checking info
checking_billing:
  order_card_holder_first_name: 'q'
  order_card_holder_mi_name: 'a'
  order_card_holder_last_name: 'automation'
  order_bank_name: 'NCSA'
  order_routing_number: '123456789'
  order_account_number: '1234567890'
  order_account_holder_phone: '4445556666'
  order_account_holder_email: 'automation@ncsasports.org'
  order_billing_address: '1333 N Kingsbury'
  order_billing_city: 'Chicago'
  order_billing_zip: '60642'

# Browser viewport sizes
viewport:
  desktop:
    width: 1270
    height: 650
  ipad:
    width: 768
    height: 650
  iphone:
    width: 400
    height: 650

# Applitool keys
applitool:
  apikey: 'GFQTsnb1ZrKslZ1T217BddUZ2tp0UaB9geadrZ8uGYg110'
  viewkey: 'P9zuZaromHL6j9e8lpKsn1v6V107glO5IhPLIY1rDT51E110'

# Daily Monitor start points
pages:
  coach_rms_login: 'http://coach-qa.ncsasports.org/coach/coachrms/login'
  contact_us_page: 'http://www.ncsasports.org/contact-us-address'
  cost_page: 'http://www.ncsasports.org/who-is-ncsa/what-does-ncsa-do/what-does-ncsa-cost-how-much'
  events_page: 'http://www.ncsasports.org/events'
  fasttrack_login: 'http://qa.ncsasports.org/fasttrack/Welcome.do'
  free_demo_request: 'http://www.ncsasports.org/team/getting-started-form'
  home_page: 'http://www.ncsasports.org/'
  partners_page: 'http://www.ncsasports.org/who-is-ncsa/how-ncsa-works/ncsas-partners'
  press_media_page: 'http://www.ncsasports.org/about-us/press-media'
  review_page: 'http://www.ncsasports.org/ncsa-reviews'
  site_map: 'http://www.ncsasports.org/sitemap.xml'
  sport_engine_webform: 'http://www.ncsasports.org/lp/sports-engine-team-edition-getting-started-form'
  ted_page: 'http://www.ncsasports.org/team'
  user_login: 'https://qa.ncsasports.org/clientrms/user_accounts/sign_in'

TED_coach_app:
  login_staging: 'https://team-staging.ncsasports.org/sign_in'
  login_prod: 'https://team.ncsasports.org/sign_in'
