# Clientrms:
clientrms:
  login_page:

# Fasttrack Admin login
fasttrack:
  login_page:
  admin_username:
  admin_password:

# TED coach/partner login
ted:
  login_page:
  prem_username:
  prem_password:
  free_username:
  free_password:
  no_content_username:
  no_content_password:
  partner_username:
  partner_password:
  api_base:

# sample video user login
video_user:
  username:
  password:

# Coach RMS
coach_rms:
  login_page:
  username:
  password:
