# Clientrms:
clientrms:
  login_page:

# Fasttrack Admin login
fasttrack:
  login_page:
  admin_username:
  admin_password:

# TED coach/partner login
ted:
  base_url: 'http://localhost:8080/'
  prem_username: 'ncsa.automation+ted@gmail.com'
  prem_password: 'password'
  free_username: 'mia@example.com'
  free_password: 'password'
  no_content_username:
  no_content_password:
  partner_username: 'john@example.com'
  partner_password: 'password'
  api_base: 'http://localhost:3000/api/team_edition/'

# sample video user login
video_user:
  username:
  password:

# Coach RMS
coach_rms:
  login_page:
  username:
  password:
