# Clientrms:
clientrms:
  base_url: 'https://pp.ncsasports.org/'
  rss_endpoint: 'api/submit/v1/new_recruit'
  login_page: 'clientrms/user_accounts/sign_in'
  offerings_page: 'clientrms/membership/offerings'
  commitment_page: 'clientrms/membership/commitment'
  payments_page: 'clientrms/finances'
  membership_info: 'clientrms/accounts'
  dashboard: 'clientrms/dashboard/show'

rss:
  base_url: 'http://pp.ncsasports.org/'
  endpoint: 'api/submit/v1/new_recruit'

# Fasttrack Admin login
# base UI url is the same with client rms
fasttrack:
  base_url: 'http://pp.ncsasports.org/'
  login_page: 'fasttrack/Welcome.do'
  recruiting_dasboard: 'recruit/admin/dashboard'
  recruit_search_form: 'fasttrack/lead/Search.do?method=preSearch'
  admin_username: 'trea'
  admin_password: 'ncsa'
  # if we reset DB, remember to give this admin helpscout email coachehoffman@ncsasports.org

# TED coach/partner login
ted:
  base_url: 'https://team-uat.ncsasports.org/'
  prem_username: 'ncsa.automation+ted@gmail.com'
  prem_password: 'password'
  free_username: 'noel.ronnie1@yopmail.com'
  free_password: 'ncsa'
  unverified_username: 'ncsa.automation+93a6@gmail.com'
  unverified_password: 'ncsa'
  no_content_username:
  no_content_password:
  partner_username: 'ncsa.automation@gmail.com'
  partner_password: 'ncsa1333'
  api_base: 'https://pp.ncsasports.org/api/team_edition/'

# sample video user login
video_user:
  username:
  password:

# Coach RMS
coach_rms:
  login_page: 'http://coach-pp.ncsasports.org/coach/coachrms/login'
  username:
  password:
