# Clientrms:
clientrms:
  base_url: 'https://pp.ncsasports.org/'
  rss_endpoint: 'api/submit/v1/new_recruit'
  login_page: 'clientrms/user_accounts/sign_in'
  offerings_page: 'clientrms/membership/offerings'
  payments_page: 'clientrms/finances'
  dashboard: 'clientrms/dashboard/show'

# Fasttrack Admin login
# base UI url is the same with client rms
fasttrack:
  login_page: 'fasttrack/Welcome.do'
  recruit_search_form: 'fasttrack/lead/Search.do?method=preSearch'
  admin_username: 'trea'
  admin_password: 'ncsa1333'

# TED coach/partner login
ted:
  base_url: 'https://team-pp.ncsasports.org'
  prem_username:
  prem_password:
  free_username:
  free_password:
  unverified_username:
  unverified_password:
  no_content_username:
  no_content_password:
  partner_username:
  partner_password:
  api_base: 'https://pp.ncsasports.org/api/team_edition'

# sample video user login
video_user:
  username:
  password:

# Coach RMS
coach_rms:
  login_page: 'http://coach-pp.ncsasports.org/coach/coachrms/login'
  username:
  password:
