# Clientrms:
clientrms:
  base_url: 'https://recruit-match.ncsasports.org/'
  rss_endpoint: 'api/submit/v1/new_recruit'

# Fasttrack Admin login
fasttrack:
  login_page:
  admin_username:
  admin_password:

# TED coach/partner login
ted:
  base_url: 'https://team.ncsasports.org'
  prem_username:
  prem_password:
  free_username:
  free_password:
  no_content_username:
  no_content_password:
  partner_username:
  partner_password:
  api_base:

# sample video user login
video_user:
  username:
  password:

# Coach RMS
coach_rms:
  login_page:
  username:
  password:
