# Please make a .sq_database.yml file locally
# Fill in the credentials in order to execute tests

staging:
  fasttrack:
    host:
    dbname:
    username:
    password:

preprod:
  fasttrack:
    host:
    dbname:
    username:
    password:

dev:
  fasttrack:
    host:
    dbname:
    username:
    password:

prod:
  fasttrack:
    host:
    dbname:
    username:
    password:
