# Clientrms:
clientrms:
  base_url: 'https://qa.ncsasports.org/'
  rss_endpoint: 'api/submit/v1/new_recruit'
  login_page: 'clientrms/user_accounts/sign_in'
  offerings_page: 'clientrms/membership/offerings'
  payments_page: 'clientrms/finances'
  dashboard: 'clientrms/dashboard/show'

# Fasttrack Admin login
# base UI url is the same with client rms
fasttrack:
  login_page: 'fasttrack/Welcome.do'
  recruit_search_form: 'fasttrack/lead/Search.do?method=preSearch'
  admin_username: 'trea'
  admin_password: 'ncsa1333'

# TED coach/partner login
ted:
  base_url: 'https://team-staging.ncsasports.org/'
  prem_username: 'ncsa.automation+ted@gmail.com'
  prem_password: 'password'
  free_username: 'noel.ronnie1@yopmail.com'
  free_password: 'ncsa'
  unverified_username: 'ncsa.automation+93a6@gmail.com'
  unverified_password: 'ncsa'
  no_content_username:
  no_content_password:
  partner_username: 'ncsa.automation@gmail.com'
  partner_password: 'ncsa1333'
  api_base: 'https://qa.ncsasports.org/api/team_edition/'

# Coachlive
coachlive:
  base_url: 'https://data-staging.ncsasports.org/api/coachlive-be/'
  email: 'email@email.com'
  password: 'password'
  account: "ncsa"
  api_key: "26d11c0ddc892821496cec3c2e"
  base_uri: "https://data-staging.ncsasports.org"

# sample video user login
video_user:
  username: 'elite2'
  password: 'ncsa'

# Coach RMS
coach_rms:
  login_page: 'http://coach-qa.ncsasports.org/coach/coachrms/login'
  username: 'Test27217nh@gmail.com'
  password: 'ncsa1333'
