# Clientrms:
clientrms:
  base_url: 'https://qa.ncsasports.org/clientrms/'
  login_page: 'user_accounts/sign_in'
  logout_page: 'user_accounts/sign_out'
  offerings_page: 'membership/offerings'
  commitment_page: 'membership/commitment'
  payments_page: 'finances'
  membership_info: 'accounts'
  dashboard: 'dashboard/show'
  my_information: 'profile/my_information/edit'
  coaching_session: 'coaching_session_requests/new'
  academic: 'profile/academic/edit'
  physical_measurables: 'profile/physical_measurables/edit'

rss:
  base_url: 'https://qa.ncsasports.org/'
  endpoint: 'api/submit/v1/new_recruit'

# Fasttrack Admin login
# base UI url is the same with client rms
fasttrack:
  base_url: 'http://qa.ncsasports.org/'
  login_page: 'fasttrack/Welcome.do'
  recruiting_dasboard: 'recruit/admin/dashboard'
  recruit_search_form: 'fasttrack/lead/Search.do?method=preSearch'
  admin_username: 'trea'
  admin_password: 'ncsa1333'

# Coach Packet fasttrack admin and coach login
coach_packet:
  coach_packet_username:
  coach_packet_password:
  base_url: 'https://coachlive-staging.ncsasports.org/'
  app_admin_username:
  admin_username: 'fasttrackauto'
  admin_password: 'eric'

# TED coach/partner login
ted:
  base_url: 'https://team-staging.ncsasports.org/'
  prem_username: 'ncsa.automation+ted@gmail.com'
  prem_password: 'password'
  free_username: 'noel.ronnie1@yopmail.com'
  free_password: 'ncsa'
  unverified_username: 'ncsa.automation+93a6@gmail.com'
  unverified_password: 'ncsa'
  no_content_username:
  no_content_password:
  partner_username: 'ncsa.automation@gmail.com'
  partner_password: 'ncsa1333'
  api_base: 'https://qa.ncsasports.org/api/team_edition/'

# Coachlive
coachlive:
  base_uri: 'http://data-staging.ncsasports.org'
  coachlive_api: '/api/coachlive-be/'
  email: 'email@email.com'
  password: 'password'
  account: 'ncsa'
  api_key: '26d11c0ddc892821496cec3c2e'

# sample video user login
video_user:
  username: 'elite2'
  password: 'ncsa'

# Coach RMS
coach_rms:
  login_page: 'http://coach-qa.ncsasports.org/coach/coachrms/login'
  username: 'coachqa@yopmail.com'
  password: 'Ncsa123$'

# Ops Messaging Service
ops_messaging:
  athlete_email: 'ncsa.automation+helpscout@gmail.com'
  client_id: '5771950'
  coach_email: 'coachehoffman@ncsasports.org'
  base_uri: 'http://data-staging.ncsasports.org'

# HelpScout
helpscout:
  app_id: 'a0e8d5c66f47418ea427816a471fcb81'
  app_secret: 'e18281e38a894c589cc9f19bf48e7fee'
  base_url: 'https://api.helpscout.net/v2/'
  coach_ehoffman_mailbox_id: '115736'
  coach_ehoffman_mailbox_slug: '56c3f91aa842623d'
  coach_ehoffman_redis_key: 'cache:c3po:helpscout_admin_coachehoffman@ncsasports.org'

# Redis
redis:
  hostname: "redis-qa.ncsasports.org"
  port: '6379'
  db: '0'

# AWS
aws:
  base_uri: 'http://data-staging.ncsasports.org'

# Salesforce FullSB
salesforce:
  login_page: 'https://ncsa--fullsb.my.salesforce.com/'
  username: 'developers@ncsasports.org.fullsb'
  password: 'rZVMzVVoWPZEDNfzZCkttFn2'
